name: lab9_ISRPO
on:
    push: 
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build: 
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: '8.0' 
            - name: Build app
              run: dotnet build ./lab9_ISRPO/lab9_ISRPO.csproj
    test-debug: 
        needs: build
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: '8.0' 
            - name: Run test
              run: dotnet test ./lab9_ISRPO/lab9_ISRPO.csproj --configuration Debug
    test-realese: 
        needs: build
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: '8.0' 
            - name: Run test
              run: dotnet test ./lab9_ISRPO/lab9_ISRPO.csproj  --configuration Release